### ISSUE TITLE
Create Task Part

### ISSUE THREAD

**Issue by AlyssaJia** [Jonah-Roesler-Edu/ABJ-SoftSol_A02#35]
Create the task classes

**Comment by AlyssaJia** [comment]
need to finish it by Monday next class

**Comment by Jonah-Roesler-Edu** [comment]
Created task class, task utility class, task db manager class
Tasks can be created and saved and displayed in lists i HTML_Tasks
It uses dateTime-Local as it's data type for the date. It's a newer version of Java date() object. Just be aware of that because it doesn't use normal date() object methods.
